substitutions:
  device_name: 'esp8266-dj-booth-controller'
  friendly_name: 'DJ Booth Controller'

esp8266:
  board: d1_mini

packages:
  base_config: !include ./shared/base_config.yaml
  wifi: !include ./shared/wifi.yaml
  api: !include ./shared/api.yaml
  metrics: !include ./shared/metrics.yaml
  mqtt: !include ./shared/mqtt.yaml

binary_sensor:
  - platform: gpio
    name: "Button 1"
    internal: true
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "1"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "1"

  - platform: gpio
    name: "Button 2"
    internal: true
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "2"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "2"

  - platform: gpio
    name: "Button 3"
    internal: true
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "3"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "3"

  - platform: gpio
    name: "Button 4"
    internal: true
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "4"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "4"

  - platform: gpio
    name: "Button 5"
    internal: true
    pin:
      number: D8
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "5"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "5"
d
